INSERT INTO carrera (nombre) VALUES ('TUDAI');
INSERT INTO carrera (nombre) VALUES ('Ingenieria');
INSERT INTO carrera (nombre) VALUES ('TUPAR');
INSERT INTO carrera (nombre) VALUES ('Matematica');
INSERT INTO carrera (nombre) VALUES ('Fisica');
INSERT INTO carrera (nombre) VALUES ('TUARI');

INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555444, 'Pablo',    'Lopez',     '1985-03-14', 'MASCULINO', 'Tandil',         11001);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555445, 'Lucia',    'Garcia',    '1998-07-02', 'FEMENINO',  'Mar del Plata', 11002);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555446, 'Juan',     'Martinez',  '1996-01-28', 'MASCULINO', 'Buenos Aires',  11003);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555447, 'Ana',      'Perez',     '1994-09-05', 'FEMENINO',  'Tandil',         11004);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555448, 'Carlos',   'Diaz',      '1997-05-11', 'MASCULINO', 'Tandil',         11005);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555449, 'Maria',    'Sanchez',   '1993-02-22', 'FEMENINO',  'Tandil',         11006);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555450, 'Sergio',   'Romero',    '1999-06-30', 'MASCULINO', 'Tandil',         11007);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555451, 'Laura',    'Torres',    '1992-08-09', 'FEMENINO',  'Santa Fe',      11008);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555452, 'Martin',   'Gomez',     '1995-04-03', 'MASCULINO', 'Tandil',         11009);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555453, 'Paula',    'Ruiz',      '1996-09-10', 'FEMENINO',  'Tucuman',       11010);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555454, 'Jorge',    'Alvarez',   '1994-03-19', 'MASCULINO', 'Salta',          11011);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555455, 'Sofia',    'Ramirez',   '1997-06-08', 'FEMENINO',  'Entre Rios',    11012);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555456, 'Diego',    'Fernandez', '1999-02-17', 'MASCULINO', 'Tandil',         11013);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (35555457, 'Carolina', 'Acosta',    '1993-05-27', 'FEMENINO',  'Neuquen',       11014);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555458, 'Miguel',   'Benitez',   '1996-01-05', 'MASCULINO', 'Jujuy',          11015);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555459, 'Gabriela', 'Molina',    '1992-07-21', 'FEMENINO',  'Tandil',         11016);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555460, 'Hector',   'Morales',   '1998-03-07', 'MASCULINO', 'Misiones',      11017);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555461, 'Natalia',  'Cabrera',   '1993-08-15', 'FEMENINO',  'Tandil',         11018);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555462, 'Fernando', 'Herrera',   '1995-05-24', 'MASCULINO', 'Formosa',       11019);
INSERT INTO Estudiante (dni, nombre, apellido, fecha_nacimiento, genero, ciudad_residencia, num_libreta) VALUES (30555463, 'Victoria', 'Castro',    '1994-01-30', 'FEMENINO',  'San Luis',      11020);

INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555444), 1, '2020-03-10', NULL);
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555445), 1, '2021-02-15', NULL);
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555446), 2, '2022-04-20', NULL);
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555447), 3, '2019-03-01', '2024-03-25');
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555448), 1, '2021-03-05', NULL);
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555449), 4, '2020-08-12', NULL);
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555450), 2, '2022-09-01', NULL);
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555451), 5, '2019-04-01', '2023-11-20');
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555452), 1, '2021-03-15', NULL);
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555453), 3, '2020-07-20', NULL);
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555454), 6, '2021-05-18', NULL);
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555455), 2, '2022-03-22', NULL);
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555456), 1, '2023-01-30', NULL);
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555456), 4, '2021-02-28', NULL);
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555458), 5, '2020-09-10', NULL);
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555459), 1, '2018-04-05', '2024-05-15');
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555460), 6, '2022-08-08', NULL);
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555461), 2, '2021-01-25', NULL);
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555462), 3, '2020-03-02', NULL);
INSERT INTO Inscripcion (id_estudiante, id_carrera, fecha_inscripcion, fecha_egreso) VALUES ((SELECT id_estudiante FROM Estudiante WHERE dni = 30555463), 1, '2023-02-14', NULL);
